<table>
    <thead>
        <tr>
            <td>
                {{$theadContent}}
            </td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                {{$tbodyContent}}
            </td>
        </tr>
    </tbody>
</table>